app1/urls.py
from django.urls import path
from app1.views import *
app_name = 'parent'

urlpatterns = [
    path('parent/',parent,name='parent'),
    path('parent2/',parent2,name='parent2'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name = 'child'

urlpatterns = [
    path('child/',child, name = 'child'),
    path('child2/',child2, name='child2'),
    path('child3/',child3, name='child3'),
    path('child4/',child4, name='child4'),
]

project20/urls.py
from django.contrib import admin
from django.urls import path, include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def parent(request):
    return render(request, 'parent.html')

def parent2(request):
    return render(request, 'parent2.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def child(request):
    return render(request, 'child.html')

def child2(request):
    return render(request, 'child2.html')

def child3(request):
    return render(request, 'child3.html')

def child4(request):
    return render(request, 'child4.html')

templates/child.html
{% extends 'parent.html' %}
/* All properties of parent */

templates/child2.html
{% extends 'parent.html' %}
{% block title %}
<title>This is child2</title> /* Overidden */ 
{% endblock %}

{% block body_block %}
<body>
    <center>
        <h1>This is child2</h1>
    </center>

    <a href="{% url 'child:child' %}">click here to see child</a>
</body>
{% endblock %}

templates/child3.html
{% extends 'parent2.html' %}
{% load static %}
{% block body_block %}
<body>
    <h1>These are additional functionality of child3 along with it's parent2 properties</h1>
    <marquee>
        <h2 style="color: brown;">Here you need to have an empty block_body tag  in body in order to add more functionalities in chilid page</h2>
    </marquee>
    <div class="card" style="width: 18rem; background-color:rgb(223, 74, 74) ">
        <img src="{% static 'images/itachi.jpg' %}" style="width:18rem;" class="card-img-top" alt="Sunset Over the Sea"/>
        <div class="card-body" style="text-align: center;">
          <p class="card-text">Itachi Uchiha of the Sharingaan</p>
        </div>
    </div>
</body>

{% endblock %}

templates/child4.html
{% extends 'parent.html' %}
{% load static %}
{% block title %}
<title>child4</title>
{% endblock %}
{% block body_block %}
<body>
    <h1>This child4</h1>
    <h2>These all  are my own features</h2>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        <div class="col">
          <div class="card h-100" style="background-color: lightblue;">
            <img src="{% static 'images/goku.png' %}" class="card-img-top" alt="Hollywood Sign on The Hill"/>
            <div class="card-body">
              <h5 class="card-title"style="color:red;">Goku</h5>
              <p class="card-text">
                This is a longer card with supporting text below as a natural lead-in to
                additional content. This content is a little bit longer.
              </p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card h-100" style="background-color: rgb(249, 106, 59);">
            <img src="{% static 'images/iron-man.png' %}" class="card-img-top" alt="Palm Springs Road"/>
            <div class="card-body">
              <h5 class="card-title" style="color: aqua;">Iron-man</h5>
              <p class="card-text">This is a short card.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card h-100" style="background-color: rgb(59, 249, 173);">
            <img src="{% static 'images/Kakashi.jpg' %}" class="card-img-top" alt="Los Angeles Skyscrapers"/>
            <div class="card-body">
              <h5 class="card-title" style="color: rgb(255, 0, 212);">Kakashi</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card h-100" style="background-color: rgb(242, 59, 157);">
            <img src="{% static 'images/spider-man.jpg' %}" class="card-img-top" alt="Skyscrapers"/>
            <div class="card-body">
              <h5 class="card-title" style="color: rgb(0, 255, 179);">Spider-man</h5>
              <p class="card-text">
                This is a longer card with supporting text below as a natural lead-in to
                additional content. This content is a little bit longer.
              </p>
            </div>
          </div>
        </div>
    </div>
    {% endblock %}
</body>

templates/parent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
      <title>Parent</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
</head>
<body>
  {% block body_block %}
    <center>
        <h1>This is parent</h1>
    </center>

    <a href="{% url 'child:child' %}">click here to see child</a>
  {% endblock %}


    <script src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>

templates/parent2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>parent2</title>
    {% endblock %}
</head>
<body>

    <h1>This is second parent parent2</h1>
    
    {% block body_block %}
       
    {% endblock %}   
</body>
</html>